name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run all
      run: docker run --rm php:5.6-cli-alpine 'composer install --dev;vendor/bin/phpunit'
